#hostapd.conf
interface=wifi
driver=nl80211
ssid=rim2025_CCS_CPP_JAS
hw_mode=a
channel=40
#wep
#auth_algs=1
#wep_default_key=0
#wep_key0="wep1234567890"
#wpa
wpa=1
wpa_passphrase=wpa1234567
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
